apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  lebels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx-container
        image: nginx-latest
        ports:
        - containerPort: 80
