#!/bin/bash

echo "================================================"
echo "     ENTERPRISE DOCKER CLI LIFECYCLE CHART      "
echo "================================================"
echo "1. BUILD STAGE (Dockerfile to Image Conversion):"
echo " Command: docker build -t my-python-app:v1 ."
echo " Architecture: Reads 'Dockerfile' layer by layer to bake an immutable server image."
echo ""
echo "2. RUN STAGE (Spinning Up The Live Container):"
echo "Command: docker run -d --name live-app-container -p 8080:80 my-python-app:v1"
echo "Architecture: Spawns an isolated microservice container running in the backgroubd (-d)."
echo ""
echo "3. AUDIT STAGE (Monitoring Active Infrastructures):"
echo " Command: docker ps -a "
echo " Architecture: Lists all live,exited,or crashed containers directly from kernel memory."
echo ""
echo "4. PURE STAGE (Destroying Dead or Obselete Nodes):"
echo " Command: docker rm -f live-app-container"
echo "Architecture: Forcefully terminates and wipes the container from hard drive allocations."
echo ""
echo "================================================"
echo "       CHART DEPLOYED BY ENGINEER SHAKIL        "
echo "================================================"
