#!/bin/bash

echo "================================================="
echo "        ENTERPRISE KUBARNETS OCHESTRATION        "
echo "================================================="
echo ""
echo "1. DEPLOYMENT STAGE (Enforcing Multi-Pod Replicase):"
echo "   Command: kubectl apply -f deployment.yaml"
echo "   Architecture: Instructs the K8s master node to spin up 3 indentical Pod replicase."
echo ""
echo "2. AUDIT STAGE (Scanning Cluster Topology):"
echo "   Command: kubectl get pod -o wide"
echo "   Architecture: Fetches real-time status and internal cloud IPs for all running Pod container."
echo ""
echo "3. SELF-HEALING SIMULATION (Automated Failure Recovery):"
echo "   Command: kubectl delete pod web-app-pod-xyz"
echo "   Architecture: When a Pod dies, K8s immediately spins up a new fresh Pod to maintain the replica state."
echo ""
echo "4. NETWORKING STAGE (Exposing Infrastructure to Global Traffic):"
echo "   Command: kubectl expose deployment web-app --type=LoadBlancer --port=80"
echo "   Architecture: Mounts a public cloud IP distributing massive user traffic across operational Pod nodes."
echo ""
echo "================================================="
echo "          K8S CLUSTER MAPPED BY SHAKIL           "
echo "================================================="
